export const GET_STOCKS = "GET_STOCKS";
export const OPEN_BUY_STOCK_DIALOG = "OPEN_BUY_STOCK_DIALOG";
export const CLOSE_BUY_STOCK_DIALOG = "CLOSE_BUY_STOCK_DIALOG";
export const OPEN_SELL_STOCK_DIALOG = "OPEN_SELL_STOCK_DIALOG";
export const CLOSE_SELL_STOCK_DIALOG = "CLOSE_SELL_STOCK_DIALOG";
export const CHANGE_STOCK_QTY = "CHANGE_STOCK_QTY";
export const INCREASE_STOCK = "INCREASE_STOCK";
